# Generated by Django 4.2.17 on 2025-01-01 14:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest_remove_about_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
